name: Create Issue on TruffleHog Findings

on:
  workflow_run:
    workflows: ["TruffleHog Scan"]
    types:
      - completed

permissions:
  issues: write

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Secrets
        run: |
          if [[ "${{ needs.trufflehog.outputs.SECRETS_FOUND }}" == "true" ]]; then
            echo "🚨 Segredos detectados. Criando um GitHub Issue..."

            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/donodorepositorio/nomedorepositorio/issues \
              -d '{
                "title": "⚠️ TruffleHog Encontrou Segredos!",
